#!/usr/bin/env python3
"""
compare_keys.py

Usage:
  python compare_keys.py path/to/file.cpp path/to/file.ts output.md

Scans the C++ and TypeScript files for key definitions, compares them,
and writes a Markdown report listing keys only in C++ and only in TypeScript.

C++ pattern expected (examples):
  {"A", KeyCode::A},
  { "Enter", KeyCode::Enter },

TypeScript pattern expected (examples):
  Numpad5 = 'Numpad5',
  Enter = 'Enter',

The script is robust to whitespace and simple inline comments.
"""

import re
import sys
from pathlib import Path

# Regex to capture C++ entries like: {"A", KeyCode::A},
CPP_PATTERN = re.compile(
    r'\{\s*["\'](?P<label>[^"\']+)["\']\s*,\s*KeyCode::(?P<key>[A-Za-z0-9_]+)\s*\}\s*,?'
)

# Regex to capture TS entries like: Numpad5 = 'Numpad5',
TS_PATTERN = re.compile(
    r'(?P<key>[A-Za-z0-9_]+)\s*=\s*["\'](?P<label>[^"\']+)["\']\s*,?'
)

def extract_cpp_keys(text):
    """Return set of key names extracted from KeyCode::... in C++ file."""
    keys = set()
    for m in CPP_PATTERN.finditer(text):
        keys.add(m.group('key'))
    return keys

def extract_ts_keys(text):
    """Return set of key names extracted from TS file (left-hand side enum names)."""
    keys = set()
    for m in TS_PATTERN.finditer(text):
        # prefer the left-hand side key name (enum name)
        keys.add(m.group('key'))
    return keys

def read_file(path):
    return Path(path).read_text(encoding='utf-8')

def write_markdown(out_path, only_cpp, only_ts, cpp_example_lines=None, ts_example_lines=None):
    lines = []
    lines.append("# Key Comparison Report\n")
    lines.append("Generated by compare_keys.py\n")
    lines.append("## Keys present in C++ but not in TypeScript\n")
    if only_cpp:
        lines.append("| Key |\n|---:|\n")
        for k in sorted(only_cpp):
            lines.append(f"| {k} |\n")
    else:
        lines.append("None. ✅\n")
    lines.append("\n## Keys present in TypeScript but not in C++\n")
    if only_ts:
        lines.append("| Key |\n|---:|\n")
        for k in sorted(only_ts):
            lines.append(f"| {k} |\n")
    else:
        lines.append("None. ✅\n")
    # optional examples
    if cpp_example_lines:
        lines.append("\n## Sample C++ matches (first 10)\n")
        lines.extend(line.rstrip() + "\n" for line in cpp_example_lines[:10])
    if ts_example_lines:
        lines.append("\n## Sample TypeScript matches (first 10)\n")
        lines.extend(line.rstrip() + "\n" for line in ts_example_lines[:10])

    Path(out_path).write_text(''.join(lines), encoding='utf-8')

def main():
    if len(sys.argv) != 3:
        print("Usage: python compare_keys.py path/to/file.cpp path/to/file.ts")
        sys.exit(2)

    cpp_path, ts_path = sys.argv[1], sys.argv[2]
    out_path = './output.md'
    cpp_text = read_file(cpp_path)
    ts_text = read_file(ts_path)

    cpp_keys = extract_cpp_keys(cpp_text)
    ts_keys = extract_ts_keys(ts_text)

    only_cpp = cpp_keys - ts_keys
    only_ts = ts_keys - cpp_keys

    # collect example matched lines for debugging in report
    cpp_examples = CPP_PATTERN.findall(cpp_text)
    ts_examples = TS_PATTERN.findall(ts_text)

    # Optional: Normalize some common differences (e.g., Numpad vs NumPad) if required.
    write_markdown(out_path, only_cpp, only_ts, cpp_example_lines=[m[0] for m in cpp_examples], ts_example_lines=[f"{m[0]} = '{m[1]}'," for m in ts_examples])

    print(f"Report written to {out_path}")
    if only_cpp:
        print(f"Keys only in C++ ({len(only_cpp)}): {sorted(only_cpp)[:10]}{'...' if len(only_cpp)>10 else ''}")
    if only_ts:
        print(f"Keys only in TS ({len(only_ts)}): {sorted(only_ts)[:10]}{'...' if len(only_ts)>10 else ''}")

if __name__ == '__main__':
    main()
